stages:
  - testing

testing:
  image: ocireg.spectrumk.de/hub.docker.com/library/python:3.9
  stage: testing
  interruptible: true
  before_script:
      - pip install poetry pytest
      - poetry export --format requirements.txt > /builds/eva4/cqapi/requirements.txt
      - pip install /builds/eva4/cqapi/
  script:
      - pytest /builds/eva4/cqapi/tests
