[tool.poetry]
name = "cqapi"
version = "0.1.0"
description = ""
authors = ["InGef - EVA Team <eva@ingef.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
ipython = "8.8.0"
pandas = "1.5.3"
numpy = "1.20.3"
requests = "^2.28.2"
attrs = "^22.2.0"
tabulate = "^0.9.0"
typeguard = "^2.13.3"
setuptools = "^66.1.0"
pyarrow = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
